# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: rubi/

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: rubi/docs/source/conf.py
  fail_on_warning: false