pair_name: "DAI/USDC"
starting_base_asset_amount: "1000"
starting_quote_asset_amount: "1000"
fair_price: "1"
price_tick: "0.00005"
grid_range: "0.0020"
spread: "0.0001"
min_level_size_in_base: "100"
min_order_size_in_base: "50"
min_transaction_size_in_base: "200"