# Auto deploys rubi-py to Test and PyPi when something is pushed into master

name: Continous Delivery to Test and PyPi for rubi-py

on:
    push:
      branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest